### ISSUE TITLE
cannot start a process twice

### ISSUE THREAD

**Issue by Benoculars** [Plazmaz/Sublist3r#13] opened 2017-09-30 18:29 UTC
Simply running py sublist3r.py -v -d exmaple.com gives this error:

```
Traceback (most recent call last):
  File "sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "sublist3r.py", line 59, in main
    return scanner.scan()
  File "C:\Users\Ben\Desktop\Sublist3r-master\Sublist3r-master\subscann3r.py", line 88, in scan
    enum.start()
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 99, in start
    assert self._popen is None, 'cannot start a process twice'
AttributeError: 'BaiduEnum' object has no attribute '_popen'
```

This is on Windows 10, Python 3.6.1

**Comment by Plazmaz** [comment] 2017-10-02 16:06
Will take a look ASAP, thanks.

**Comment by Plazmaz** [comment] 2017-10-06 19:37
Should be resolved by #15! Let me know if that's not true.

**Comment by Benoculars** [comment] 2017-10-07 22:31
Hmm, still getting the same error even with the fix.

**Comment by Plazmaz** [comment] 2017-12-12 19:32
@Benoculars sorry for the late response, but is this still an issue? I'm unable to reproduce it on my Ubuntu python 3 machine.

**Closed as completed** 2019-02-03 23:11 UTC

**Comment by Plazmaz** [comment] 2019-02-03 23:13
Should be resolved.
